### ISSUE TITLE
No such property: packageName

### ISSUE THREAD

**Issue by zackb** [kenshoo/gradle-fpm-plugin#13]
Using 0.4 and trying to change the packageName property. Getting:

Caused by: groovy.lang.MissingPropertyException: No such property: packageName for class: com.kenshoo.watership.PackagingPluginExtension_Decorated
	at org.gradle.api.internal.plugins.ExtraPropertiesDynamicObjectAdapter.setProperty(ExtraPropertiesDynamicObjectAdapter.java:46)
	at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:119)
	at com.kenshoo.watership.PackagingPluginExtension_Decorated.setProperty(Unknown Source)
	at build_asnd37g27vuhlvk6mypvtdxw$_run_closure5.doCall(/Users/zack/Code/dlvr/acme/build.gradle:68)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_asnd37g27vuhlvk6mypvtdxw.run(/Users/zack/Code/dlvr/acme/build.gradle:67)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)

**Comment by tzachz** [comment]
@zackb packageName was only [added](https://github.com/kenshoo/gradle-fpm-plugin/commit/8e3728f767bdf0e8cd0cad367c6e7faa29121bed) in version 0.5. In version 0.4 the package cannot be changed, so you'll either have to upgrade or leave it with the default value.

**Comment by william-poitras** [comment]
Is 0.5 published anywhere?

**Comment by tzachz** [comment]
@william-poitras - oh, apparently it isn't. I'll let you know when it is.

**Comment by tzachz** [comment]
@william-poitras Sorry for the delay, it's available now: http://mvnrepository.com/artifact/com.kenshoo/gradle-fpm/0.5
